source 'https://rubygems.org'

gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '~> 8.0', require: false
gem 'rake', '~> 13.0'

group :development, :test do
  gem 'puppetlabs_spec_helper', '~> 8.0'
  gem 'rspec-puppet', '>= 4.0'
  gem 'puppet-lint', '~> 4.0'
  gem 'metadata-json-lint', '~> 4.0'
end
